<?php

namespace SccBundle\Repository;

/**
 * addEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class addEventRepository extends \Doctrine\ORM\EntityRepository
{
}
