<?php

namespace SccBundle\Repository;

use Symfony\Component\EventDispatcher\Event;
use Symfony\Component\HttpFoundation\Request;
use ADesigns\CalendarBundle\Entity\EventEntity as BaseCalendar;
/**
 * addEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class addEventRepository extends BaseCalendar
{
}
